name: food_order_app
description: "Food Order App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/json/dataset.json



 